name: Build Debian 13 Qcow2 Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x build.sh

      - name: Run Build Script
        run: sudo ./build.sh

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Debian 13 UEFI Qcow2 Minimal"
          body: |
            ### 极致精简版 QCOW2 镜像
            - **OS**: Debian 13 (Trixie) Cloud-Kernel
            - **格式**: qcow2 (内置 zlib 压缩)
            - **文件系统**: Btrfs (zstd:3)
            - **密码**: `password`
          # 核心：修改为生成的 qcow2 文件名
          files: debian-uefi.qcow2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
