name: Build Debian 13 UEFI Image

on:
  workflow_dispatch: # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须开启写入权限

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build Script
        run: sudo ./build.sh

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Debian 13 UEFI Btrfs Networkd"
          body: |
            ### 镜像信息
            - **OS**: Debian 13 (Trixie)
            - **FS**: Btrfs (zstd:3)
            - **Network**: systemd-networkd + resolved
            - **Password**: `password`
          # 核心：必须匹配 build.sh 最后的压缩文件名
          files: debian13-uefi-networkd.raw.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
